export const SESSION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ACTIVE_LEVEL_1: 'ACTIVE_LEVEL_1',
  COMPLETED_LEVEL_1: 'COMPLETED_LEVEL_1',
  ACTIVE_LEVEL_2: 'ACTIVE_LEVEL_2',
  COMPLETED_LEVEL_2: 'COMPLETED_LEVEL_2',
  ACTIVE_LEVEL_3: 'ACTIVE_LEVEL_3',
  COMPLETED: 'COMPLETED',
  ELIMINATED: 'ELIMINATED',
};

export const STATUS_ROUTE_MAP = {
  [SESSION_STATUS.ACTIVE_LEVEL_1]: '/level/1',
  [SESSION_STATUS.COMPLETED_LEVEL_1]: '/level/1/result',
  [SESSION_STATUS.ACTIVE_LEVEL_2]: '/level/2',
  [SESSION_STATUS.COMPLETED_LEVEL_2]: '/level/2/result',
  [SESSION_STATUS.ACTIVE_LEVEL_3]: '/level/3',
  [SESSION_STATUS.COMPLETED]: '/result',
  [SESSION_STATUS.ELIMINATED]: '/result',
};

export const COMPETITION_STATUS = {
  NOT_STARTED: 'not_started',
  ACTIVE: 'active',
  PAUSED: 'paused',
  ENDED: 'ended',
};
