const SESSION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  ACTIVE_LEVEL_1: 'ACTIVE_LEVEL_1',
  COMPLETED_LEVEL_1: 'COMPLETED_LEVEL_1',
  ACTIVE_LEVEL_2: 'ACTIVE_LEVEL_2',
  COMPLETED_LEVEL_2: 'COMPLETED_LEVEL_2',
  ACTIVE_LEVEL_3: 'ACTIVE_LEVEL_3',
  COMPLETED: 'COMPLETED',
  ELIMINATED: 'ELIMINATED',
};

const VALID_TRANSITIONS = {
  [SESSION_STATUS.NOT_STARTED]: [SESSION_STATUS.ACTIVE_LEVEL_1],
  [SESSION_STATUS.ACTIVE_LEVEL_1]: [SESSION_STATUS.COMPLETED_LEVEL_1],
  [SESSION_STATUS.COMPLETED_LEVEL_1]: [SESSION_STATUS.ACTIVE_LEVEL_2],
  [SESSION_STATUS.ACTIVE_LEVEL_2]: [
    SESSION_STATUS.COMPLETED_LEVEL_2,
    SESSION_STATUS.ELIMINATED,
  ],
  [SESSION_STATUS.COMPLETED_LEVEL_2]: [SESSION_STATUS.ACTIVE_LEVEL_3],
  [SESSION_STATUS.ACTIVE_LEVEL_3]: [SESSION_STATUS.COMPLETED],
  [SESSION_STATUS.COMPLETED]: [],
  [SESSION_STATUS.ELIMINATED]: [],
};

const QUESTION_TYPES = {
  MCQ: 'mcq',
  EXIT_ROOM: 'exit_room',
  GUESS_OUTPUT: 'guess_output',
};

const COMPETITION_STATUS = {
  NOT_STARTED: 'not_started',
  ACTIVE: 'active',
  PAUSED: 'paused',
  ENDED: 'ended',
};

const ADMIN_ROLES = {
  ADMIN: 'admin',
  SUPER_ADMIN: 'super_admin',
};

const DEFAULT_CONFIG = {
  level1QuestionCount: 20,
  level1PointsPerQuestion: 5,
  level2StepCount: 3,
  level2PointsPerStep: 10,
  level2Lives: 3,
  level3QuestionCount: 5,
  level3PointsPerQuestion: 10,
  competitionStatus: COMPETITION_STATUS.NOT_STARTED,
};

module.exports = {
  SESSION_STATUS,
  VALID_TRANSITIONS,
  QUESTION_TYPES,
  COMPETITION_STATUS,
  ADMIN_ROLES,
  DEFAULT_CONFIG,
};
